/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: simpleclass.swigcxx

package simpleclass

/*
#cgo CPPFLAGS: -I /usr/include/c++/4.9/ -I /usr/local/include/gdcm-2.4/ -I /usr/include/x86_64-linux-gnu/c++/4.9/
#cgo LDFLAGS: -L /usr/local/lib/ -lgdcmMSFF -lgdcmMEXD -lsocketxx -lgdcmMSFF -lgdcmjpeg8 -lgdcmjpeg12 -lgdcmjpeg16 -lgdcmopenjpeg -lgdcmcharls -lgdcmuuid -lgdcmDICT -lgdcmIOD -lgdcmexpat -lgdcmDSED -lgdcmCommon -lgdcmzlib -ldl
*/
import "C"
