package main

import "io/ioutil"
import "net/http"
import "strconv"
import "log"
import "encoding/json"
import "errors"
import "time"
import "os"

import "encoding/base64"

const htmlData = "PCFkb2N0eXBlIGh0bWw+DQo8aHRtbD4NCg0KPGhlYWQ+DQoJPHRpdGxlPmR0b29scyBVSTwvdGl0bGU+DQoJPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+DQoJPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJodHRwczovL25ldGRuYS5ib290c3RyYXBjZG4uY29tL2Jvb3Rzd2F0Y2gvMy4wLjAvc2xhdGUvYm9vdHN0cmFwLm1pbi5jc3MiPg0KCTxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Imh0dHBzOi8vYWpheC5nb29nbGVhcGlzLmNvbS9hamF4L2xpYnMvanF1ZXJ5LzIuMC4zL2pxdWVyeS5taW4uanMiPjwvc2NyaXB0Pg0KCTxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Imh0dHBzOi8vbmV0ZG5hLmJvb3RzdHJhcGNkbi5jb20vYm9vdHN0cmFwLzMuMS4xL2pzL2Jvb3RzdHJhcC5taW4uanMiPjwvc2NyaXB0Pg0KCTxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+DQoJCWJvZHkgew0KCQkJcGFkZGluZy10b3A6IDIwcHg7DQoJCX0NCgkJLmZvb3RlciB7DQoJCQlib3JkZXItdG9wOiAxcHggc29saWQgI2VlZTsNCgkJCW1hcmdpbi10b3A6IDQwcHg7DQoJCQlwYWRkaW5nLXRvcDogNDBweDsNCgkJCXBhZGRpbmctYm90dG9tOiA0MHB4Ow0KCQl9DQoJCS8qIE1haW4gbWFya2V0aW5nIG1lc3NhZ2UgYW5kIHNpZ24gdXAgYnV0dG9uICovDQoJCQ0KCQkuanVtYm90cm9uIHsNCgkJCXRleHQtYWxpZ246IGNlbnRlcjsNCgkJCWJhY2tncm91bmQtY29sb3I6IHRyYW5zcGFyZW50Ow0KCQl9DQoJCS5qdW1ib3Ryb24gLmJ0biB7DQoJCQlmb250LXNpemU6IDIxcHg7DQoJCQlwYWRkaW5nOiAxNHB4IDI0cHg7DQoJCX0NCgkJLyogQ3VzdG9taXplIHRoZSBuYXYtanVzdGlmaWVkIGxpbmtzIHRvIGJlIGZpbGwgdGhlIGVudGlyZSBzcGFjZSBvZiB0aGUgLm5hdmJhciAqLw0KCQkNCgkJLm5hdi1qdXN0aWZpZWQgew0KCQkJYmFja2dyb3VuZC1jb2xvcjogI2VlZTsNCgkJCWJvcmRlci1yYWRpdXM6IDVweDsNCgkJCWJvcmRlcjogMXB4IHNvbGlkICNjY2M7DQoJCX0NCgkJLm5hdi1qdXN0aWZpZWQgPiBsaSA+IGEgew0KCQkJcGFkZGluZy10b3A6IDE1cHg7DQoJCQlwYWRkaW5nLWJvdHRvbTogMTVweDsNCgkJCWNvbG9yOiAjNzc3Ow0KCQkJZm9udC13ZWlnaHQ6IGJvbGQ7DQoJCQl0ZXh0LWFsaWduOiBjZW50ZXI7DQoJCQlib3JkZXItYm90dG9tOiAxcHggc29saWQgI2Q1ZDVkNTsNCgkJCWJhY2tncm91bmQtY29sb3I6ICNlNWU1ZTU7DQoJCQkvKiBPbGQgYnJvd3NlcnMgKi8NCgkJCQ0KCQkJYmFja2dyb3VuZC1yZXBlYXQ6IHJlcGVhdC14Ow0KCQkJLyogUmVwZWF0IHRoZSBncmFkaWVudCAqLw0KCQkJDQoJCQliYWNrZ3JvdW5kLWltYWdlOiAtbW96LWxpbmVhci1ncmFkaWVudCh0b3AsICNmNWY1ZjUgMCUsICNlNWU1ZTUgMTAwJSk7DQoJCQkvKiBGRjMuNisgKi8NCgkJCQ0KCQkJYmFja2dyb3VuZC1pbWFnZTogLXdlYmtpdC1ncmFkaWVudChsaW5lYXIsIGxlZnQgdG9wLCBsZWZ0IGJvdHRvbSwgY29sb3Itc3RvcCgwJSwgI2Y1ZjVmNSksIGNvbG9yLXN0b3AoMTAwJSwgI2U1ZTVlNSkpOw0KCQkJLyogQ2hyb21lLFNhZmFyaTQrICovDQoJCQkNCgkJCWJhY2tncm91bmQtaW1hZ2U6IC13ZWJraXQtbGluZWFyLWdyYWRpZW50KHRvcCwgI2Y1ZjVmNSAwJSwgI2U1ZTVlNSAxMDAlKTsNCgkJCS8qIENocm9tZSAxMCssU2FmYXJpIDUuMSsgKi8NCgkJCQ0KCQkJYmFja2dyb3VuZC1pbWFnZTogLW1zLWxpbmVhci1ncmFkaWVudCh0b3AsICNmNWY1ZjUgMCUsICNlNWU1ZTUgMTAwJSk7DQoJCQkvKiBJRTEwKyAqLw0KCQkJDQoJCQliYWNrZ3JvdW5kLWltYWdlOiAtby1saW5lYXItZ3JhZGllbnQodG9wLCAjZjVmNWY1IDAlLCAjZTVlNWU1IDEwMCUpOw0KCQkJLyogT3BlcmEgMTEuMTArICovDQoJCQkNCgkJCWZpbHRlcjogcHJvZ2lkOiBEWEltYWdlVHJhbnNmb3JtLk1pY3Jvc29mdC5ncmFkaWVudChzdGFydENvbG9yc3RyPScjZjVmNWY1JywgZW5kQ29sb3JzdHI9JyNlNWU1ZTUnLCBHcmFkaWVudFR5cGU9MCk7DQoJCQkvKiBJRTYtOSAqLw0KCQkJDQoJCQliYWNrZ3JvdW5kLWltYWdlOiBsaW5lYXItZ3JhZGllbnQodG9wLCAjZjVmNWY1IDAlLCAjZTVlNWU1IDEwMCUpOw0KCQkJLyogVzNDICovDQoJCX0NCgkJLm5hdi1qdXN0aWZpZWQgPiAuYWN0aXZlID4gYSwNCgkJLm5hdi1qdXN0aWZpZWQgPiAuYWN0aXZlID4gYTpob3ZlciwNCgkJLm5hdi1qdXN0aWZpZWQgPiAuYWN0aXZlID4gYTpmb2N1cyB7DQoJCQliYWNrZ3JvdW5kLWNvbG9yOiAjZGRkOw0KCQkJYmFja2dyb3VuZC1pbWFnZTogbm9uZTsNCgkJCWJveC1zaGFkb3c6IGluc2V0IDAgM3B4IDdweCByZ2JhKDAsIDAsIDAsIC4xNSk7DQoJCX0NCgkJLm5hdi1qdXN0aWZpZWQgPiBsaTpmaXJzdC1jaGlsZCA+IGEgew0KCQkJYm9yZGVyLXJhZGl1czogNXB4IDVweCAwIDA7DQoJCX0NCgkJLm5hdi1qdXN0aWZpZWQgPiBsaTpsYXN0LWNoaWxkID4gYSB7DQoJCQlib3JkZXItYm90dG9tOiAwOw0KCQkJYm9yZGVyLXJhZGl1czogMCAwIDVweCA1cHg7DQoJCX0NCgkJQG1lZGlhKG1pbi13aWR0aDogNzY4cHgpIHsNCgkJCS5uYXYtanVzdGlmaWVkIHsNCgkJCQltYXgtaGVpZ2h0OiA1MnB4Ow0KCQkJfQ0KCQkJLm5hdi1qdXN0aWZpZWQgPiBsaSA+IGEgew0KCQkJCWJvcmRlci1sZWZ0OiAxcHggc29saWQgI2ZmZjsNCgkJCQlib3JkZXItcmlnaHQ6IDFweCBzb2xpZCAjZDVkNWQ1Ow0KCQkJfQ0KCQkJLm5hdi1qdXN0aWZpZWQgPiBsaTpmaXJzdC1jaGlsZCA+IGEgew0KCQkJCWJvcmRlci1sZWZ0OiAwOw0KCQkJCWJvcmRlci1yYWRpdXM6IDVweCAwIDAgNXB4Ow0KCQkJfQ0KCQkJLm5hdi1qdXN0aWZpZWQgPiBsaTpsYXN0LWNoaWxkID4gYSB7DQoJCQkJYm9yZGVyLXJhZGl1czogMCA1cHggNXB4IDA7DQoJCQkJYm9yZGVyLXJpZ2h0OiAwOw0KCQkJfQ0KCQl9DQoJCS8qIFJlc3BvbnNpdmU6IFBvcnRyYWl0IHRhYmxldHMgYW5kIHVwICovDQoJCQ0KCQlAbWVkaWEgc2NyZWVuIGFuZChtaW4td2lkdGg6IDc2OHB4KSB7DQoJCQkvKiBSZW1vdmUgdGhlIHBhZGRpbmcgd2Ugc2V0IGVhcmxpZXIgKi8NCgkJCQ0KCQkJLm1hc3RoZWFkLA0KCQkJLm1hcmtldGluZywNCgkJCS5mb290ZXIgew0KCQkJCXBhZGRpbmctbGVmdDogMDsNCgkJCQlwYWRkaW5nLXJpZ2h0OiAwOw0KCQkJfQ0KCQl9DQoJPC9zdHlsZT4NCgk8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+DQoJCXZhciBjZlRpbWUgPSBuZXcgRGF0ZSgpOw0KCQl2YXIgY3VyZGlyID0gIiINCgkJdmFyIGRpc0FsaXZlID0gdHJ1ZQ0KCQl2YXIgU2hvd01lbnUgPSAic2VhcmNoIg0KCQl2YXIgY1VwbG9hZEYgPSAiIg0KDQoJCWZ1bmN0aW9uIHVwZGF0ZUNFY2hvU3QoKSB7DQoJCQl2YXIgY0VDaG9SZXEgPSB7DQoJCQkJQWRkcmVzczogJCgiI2FkZHJlc3MtaWQiKS52YWwoKSwNCgkJCQlQb3J0OiAkKCIjcG9ydC1pZCIpLnZhbCgpLA0KCQkJCVNlcnZlckFFX1RpdGxlOiAkKCIjYWV0aXRsZS1pZCIpLnZhbCgpDQoJCQl9Ow0KCQkJJC5hamF4KHsNCgkJCQl1cmw6ICIvYy1lY2hvIiwNCgkJCQl0eXBlOiAiUE9TVCIsDQoJCQkJZGF0YTogSlNPTi5zdHJpbmdpZnkoY0VDaG9SZXEpLA0KCQkJCWRhdGFUeXBlOiAianNvbiINCgkJCX0pLmRvbmUoZnVuY3Rpb24oanNvbkRhdGEpIHsNCgkJCQlkaXNBbGl2ZSA9IGpzb25EYXRhLklzQWxpdmUNCgkJCQl1cGRhdGVVaSgpDQoJCQl9KQ0KCQl9DQoNCgkJZnVuY3Rpb24gdXBkYXRlVWkoKSB7DQoJCQlpZiAoZGlzQWxpdmUpIHsNCgkJCQkkKCIjcGFjcy1zdGF0dXMtaWQiKS50ZXh0KCJvayIpDQoJCQl9IGVsc2Ugew0KCQkJCSQoIiNwYWNzLXN0YXR1cy1pZCIpLnRleHQoIm5vIGNvbm5lY3Rpb24iKQ0KCQkJfQ0KCQkJaWYgKGRpc0FsaXZlICYmIChTaG93TWVudSA9PSAic2VhcmNoIikpIHsNCgkJCQkkKCIjc2VhcmNoLXBhbmVsIikuc2hvdygpDQoJCQkJJCgiI3NlYXJjaC1mb290ZXIiKS5zaG93KCkNCgkJCQkkKCIjc2VyZm9vdGVyLWlkIikuc2hvdygpDQoJCQkJJCgiI3NlcnRhYmxlLWlkIikuc2hvdygpDQoJCQl9IGVsc2Ugew0KCQkJCSQoIiNzZWFyY2gtcGFuZWwiKS5oaWRlKCk7DQoJCQkJJCgiI3NlYXJjaC1mb290ZXIiKS5oaWRlKCkNCgkJCQkkKCIjc2VyZm9vdGVyLWlkIikuaGlkZSgpDQoJCQkJJCgiI3NlcnRhYmxlLWlkIikuaGlkZSgpDQoJCQl9DQoJCQlpZiAoZGlzQWxpdmUgJiYgKFNob3dNZW51ID09ICJ1cGxvYWQiKSkgew0KCQkJCSQoIiNmaWxlcy10YWIiKS5zaG93KCkNCgkJCQkkKCIjdXBsb2FkZm9vdGVyLWlkIikuc2hvdygpDQoJCQl9IGVsc2Ugew0KCQkJCSQoIiN1cGxvYWRmb290ZXItaWQiKS5oaWRlKCkNCgkJCQkkKCIjZmlsZXMtdGFiIikuaGlkZSgpDQoJCQl9DQoJCQlpZiAoZGlzQWxpdmUgJiYgKFNob3dNZW51ID09ICJqb2JzIikpIHsNCgkJCQkkKCIjam9ic2xpc3Rmb290ZXItaWQiKS5zaG93KCkNCgkJCQkkKCIjam9ic2xpc3QiKS5zaG93KCkNCgkJCX0gZWxzZSB7DQoJCQkJJCgiI2pvYnNsaXN0Zm9vdGVyLWlkIikuaGlkZSgpDQoJCQkJJCgiI2pvYnNsaXN0IikuaGlkZSgpDQoJCQl9DQoJCX0NCg0KCQlmdW5jdGlvbiBzZW5kQ0ZpbmQoKSB7DQoJCQl1cGRhdGVKb2JzKCkNCgkJCXZhciBjZmRhdCA9IHsNCgkJCQlTZXJ2ZXJTZXQ6IHsNCgkJCQkJQWRkcmVzczogJCgiI2FkZHJlc3MtaWQiKS52YWwoKSwNCgkJCQkJUG9ydDogJCgiI3BvcnQtaWQiKS52YWwoKSwNCgkJCQkJU2VydmVyQUVfVGl0bGU6ICQoIiNhZXRpdGxlLWlkIikudmFsKCkNCgkJCQl9LA0KCQkJCVN0dWR5SW5zdGFuY2VVSUQ6ICQoIiNzdC1pbnN0LXVpZCIpLnZhbCgpLA0KCQkJCVBhdGllbnROYW1lOiAkKCIjcGF0aWVudC1uYW1lLWlkIikudmFsKCksDQoJCQkJQWNjZXNzaW9uTnVtYmVyOiAkKCIjYWNjZXNzaW9uLW51bWJlci1pZCIpLnZhbCgpLA0KCQkJCVBhdGllbkRhdGVPZkJpcnRoOiAkKCIjZGF0ZS1iaXJ0aC1pZCIpLnZhbCgpLA0KCQkJCVN0dWR5RGF0ZTogJCgiI3N0dWR5LWRhdGUtaWQiKS52YWwoKQ0KCQkJfTsNCgkJCSQuYWpheCh7DQoJCQkJdXJsOiAiL2MtZmluZCIsDQoJCQkJdHlwZTogIlBPU1QiLA0KCQkJCWRhdGE6IEpTT04uc3RyaW5naWZ5KGNmZGF0KSwNCgkJCQlkYXRhVHlwZTogImpzb24iDQoJCQl9KQ0KCQl9DQoNCgkJZnVuY3Rpb24gY3JlYXRlVVVJRCgpIHsNCgkJCS8vIGh0dHA6Ly93d3cuaWV0Zi5vcmcvcmZjL3JmYzQxMjIudHh0DQoJCQl2YXIgcyA9IFtdOw0KCQkJdmFyIGhleERpZ2l0cyA9ICIwMTIzNDU2Nzg5QUJDREVGIjsNCgkJCWZvciAodmFyIGkgPSAwOyBpIDwgMzI7IGkrKykgew0KCQkJCXNbaV0gPSBoZXhEaWdpdHMuc3Vic3RyKE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIDB4MTApLCAxKTsNCgkJCX0NCgkJCXNbMTJdID0gIjQiOyAvLyBiaXRzIDEyLTE1IG9mIHRoZSB0aW1lX2hpX2FuZF92ZXJzaW9uIGZpZWxkIHRvIDAwMTANCgkJCXNbMTZdID0gaGV4RGlnaXRzLnN1YnN0cigoc1sxNl0gJiAweDMpIHwgMHg4LCAxKTsgLy8gYml0cyA2LTcgb2YgdGhlIGNsb2NrX3NlcV9oaV9hbmRfcmVzZXJ2ZWQgdG8gMDENCgkJCXZhciB1dWlkID0gcy5qb2luKCIiKTsNCgkJCXJldHVybiB1dWlkOw0KCQl9DQoNCgkJZnVuY3Rpb24gdXBkYXRlQ0ZpbmRTdCgpIHsNCgkJCSQuYWpheCh7DQoJCQkJdXJsOiAiL2MtZmluZGRhdCIsDQoJCQkJdHlwZTogIlBPU1QiLA0KCQkJCWRhdGE6IEpTT04uc3RyaW5naWZ5KGNmVGltZSksDQoJCQkJZGF0YVR5cGU6ICJqc29uIg0KCQkJfSkuZG9uZShmdW5jdGlvbihqc29uRGF0YSkgew0KCQkJCWlmIChqc29uRGF0YS5SZWZyZXNoKSB7DQoJCQkJCWNmVGltZSA9IGpzb25EYXRhLkZUaW1lDQoJCQkJCSQoIiNzZXJjaHJlc2xpc3QiKS5yZW1vdmUoKQ0KCQkJCQl2YXIgaW5lckh0bWwgPSAiIg0KCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRib2R5IGlkPSJzZXJjaHJlc2xpc3QiPicpDQoJCQkJCWZvciAoaW5kZXggaW4ganNvbkRhdGEuQ2ZpbmRSZXMpIHsNCgkJCQkJCWFuID0ganNvbkRhdGEuQ2ZpbmRSZXNbaW5kZXhdLkFjY2Vzc2lvbk51bWJlcg0KCQkJCQkJcGQgPSBqc29uRGF0YS5DZmluZFJlc1tpbmRleF0uUGF0aWVuRGF0ZU9mQmlydGgNCgkJCQkJCXNkID0ganNvbkRhdGEuQ2ZpbmRSZXNbaW5kZXhdLlN0dWR5RGF0ZQ0KCQkJCQkJcG4gPSBqc29uRGF0YS5DZmluZFJlc1tpbmRleF0uUGF0aWVudE5hbWUNCgkJCQkJCXN0dWlkID0ganNvbkRhdGEuQ2ZpbmRSZXNbaW5kZXhdLlN0dWR5SW5zdGFuY2VVSUQNCgkJCQkJCWd1ID0gY3JlYXRlVVVJRCgpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRyPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRkPjxhIGlkPSInICsgZ3UgKyAnIiBvbmNsaWNrPSJzZW5kQ0dldCh0aGlzKSIgY2xhc3M9ImJ0biBwdWxsLWxlZnQgYnRuLXN1Y2Nlc3MgYnRuLXhzIj5Eb3dubG9hZDwvYT48L3RkPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRkIGlkPSInICsgJ3N0dWlkJyArIGd1ICsgJyIgPicgKyBzdHVpZCArICc8L3RkPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRkIGlkPSInICsgJ2FuJyArIGd1ICsgJyIgPicgKyBhbiArICc8L3RkPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRkIGlkPSInICsgJ3BuJyArIGd1ICsgJyIgPicgKyBwbiArICc8L3RkPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRkIGlkPSInICsgJ3BkJyArIGd1ICsgJyIgPicgKyBwZCArICc8L3RkPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPHRkIGlkPSInICsgJ3NkJyArIGd1ICsgJyIgPicgKyBzZCArICc8L3RkPicpDQoJCQkJCQlpbmVySHRtbCA9IGluZXJIdG1sLmNvbmNhdCgnPC90cj4nKQ0KCQkJCQl9DQoJCQkJCWluZXJIdG1sID0gaW5lckh0bWwuY29uY2F0KCcgPC90Ym9keT4nKQ0KCQkJCQkkKCIjc2VydGFibGUtaWQiKS5hcHBlbmQoaW5lckh0bWwpDQoJCQkJCWNvbnNvbGUubG9nKGpzb25EYXRhLkNmaW5kUmVzKQ0KCQkJCX0gZWxzZSB7DQoJCQkJCS8vY29uc29sZS5sb2coIm5vIG5lZWQgdG8gdXBkYXRlIikNCgkJCQl9DQoJCQl9KQ0KCQl9DQoNCgkJZnVuY3Rpb24gY2hEaXIoZSkgew0KCQkJdmFyIG5EaXIgPSB7DQoJCQkJTmV3OiBlLmlkLA0KCQkJCUN1ckRpcjogY3VyZGlyDQoJCQl9Ow0KCQkJJC5hamF4KHsNCgkJCQl1cmw6ICIvY2hkIiwNCgkJCQl0eXBlOiAiUE9TVCIsDQoJCQkJZGF0YVR5cGU6ICJqc29uIiwNCgkJCQlkYXRhOiBKU09OLnN0cmluZ2lmeShuRGlyKQ0KCQkJfSkuZG9uZShkaXJVcGRhdGUpDQoJCX0NCg0KCQlmdW5jdGlvbiBmaXJzVXBkYXRlKCkgew0KCQkJdmFyIG5EaXIgPSB7DQoJCQkJTmV3OiAiLiIsDQoJCQkJQ3VyRGlyOiAiLiINCgkJCX07DQoJCQkkLmFqYXgoew0KCQkJCXVybDogIi9jaGQiLA0KCQkJCXR5cGU6ICJQT1NUIiwNCgkJCQlkYXRhVHlwZTogImpzb24iLA0KCQkJCWRhdGE6IEpTT04uc3RyaW5naWZ5KG5EaXIpDQoJCQl9KS5kb25lKGRpclVwZGF0ZSkNCgkJfQ0KDQoJCWZ1bmN0aW9uIGRpclVwZGF0ZShqc29uRGF0YSkgew0KCQkJJCgiI2ZpbGVzLWlkIikucmVtb3ZlKCkNCgkJCWN1cmRpciA9IGpzb25EYXRhLkN1ckRpcg0KCQkJY29uc29sZS5sb2coanNvbkRhdGEpDQoJCQl2YXIgaW5lckh0bWxmaWxlcyA9ICIiDQoJCQlpbmVySHRtbGZpbGVzID0gaW5lckh0bWxmaWxlcy5jb25jYXQoJzx0Ym9keSBpZD0iZmlsZXMtaWQiPicpDQoJCQlpbmVySHRtbGZpbGVzID0gaW5lckh0bWxmaWxlcy5jb25jYXQoJzx0cj48dGQ+PC90ZD4nKQ0KCQkJaW5lckh0bWxmaWxlcyA9IGluZXJIdG1sZmlsZXMuY29uY2F0KCc8dGQgb25jbGljaz0iY2hEaXIodGhpcykiIGlkPSIuLiI+PGltZyBzcmM9Imh0dHA6Ly91cGxvYWQud2lraW1lZGlhLm9yZy93aWtpcGVkaWEvY29tbW9ucy9kL2RjL0JsdWVfZm9sZGVyX3NldGhfeWFzdHJvdl8wMS5zdmciIHdpZHRoPSIzMCIgYWx0PSJsb3JlbSI+Li48L3RkPjwvdHI+JykNCgkJCWZvciAoaW5kZXggaW4ganNvbkRhdGEuRmlsZXMpIHsNCgkJCQlubSA9IGpzb25EYXRhLkZpbGVzW2luZGV4XS5OYW1lDQoJCQkJZGkgPSBqc29uRGF0YS5GaWxlc1tpbmRleF0uSXNEaXINCgkJCQlpZiAoanNvbkRhdGEuRmlsZXNbaW5kZXhdLklzRGlyKSB7DQoJCQkJCWluZXJIdG1sZmlsZXMgPSBpbmVySHRtbGZpbGVzLmNvbmNhdCgnPHRyIHdpZHRoPSI1Ij48dGQ+PGEgIG9uY2xpY2s9InNlbmRDU3RvcmUodGhpcykiIGlkPSInICsgJ2ZpJyArIG5tICsgJy8iIGNsYXNzPSJidG4gcHVsbC1sZWZ0IGJ0bi1zdWNjZXNzIGJ0bi14cyI+VXBsb2FkPC9hPjwvdGQ+JykNCgkJCQkJaW5lckh0bWxmaWxlcyA9IGluZXJIdG1sZmlsZXMuY29uY2F0KCc8dGQgb25jbGljaz0iY2hEaXIodGhpcykiICcgKyAnaWQ9IicgKyBubSArICciPjxpbWcgc3JjPSJodHRwOi8vdXBsb2FkLndpa2ltZWRpYS5vcmcvd2lraXBlZGlhL2NvbW1vbnMvZC9kYy9CbHVlX2ZvbGRlcl9zZXRoX3lhc3Ryb3ZfMDEuc3ZnIiB3aWR0aD0iMzAiIGFsdD0ibG9yZW0iPicgKyBubSArICc8L3RkPjwvdHI+JykNCgkJCQl9IGVsc2Ugew0KCQkJCQlpbmVySHRtbGZpbGVzID0gaW5lckh0bWxmaWxlcy5jb25jYXQoJzx0ciB3aWR0aD0iNSI+PHRkPjxhICBvbmNsaWNrPSJzZW5kQ1N0b3JlKHRoaXMpIiBpZD0iJyArICdmaScgKyBubSArICciIGNsYXNzPSJidG4gcHVsbC1sZWZ0IGJ0bi1zdWNjZXNzIGJ0bi14cyI+VXBsb2FkPC9hPjwvdGQ+JykNCgkJCQkJaW5lckh0bWxmaWxlcyA9IGluZXJIdG1sZmlsZXMuY29uY2F0KCc8dGQgb25jbGljaz0iY2hEaXIodGhpcykiICcgKyAnaWQ9IicgKyBubSArICciPjxpbWcgc3JjPSJodHRwOi8vd3d3LmZyZWVjYWR3ZWIub3JnL3dpa2kvaW1hZ2VzLzIvMjkvRG9jdW1lbnQtbmV3LnN2ZyIgd2lkdGg9IjMwIiBhbHQ9ImxvcmVtIj4nICsgbm0gKyAnPC90ZD48L3RyPicpDQoJCQkJfQ0KCQkJfQ0KCQkJaW5lckh0bWxmaWxlcyA9IGluZXJIdG1sZmlsZXMuY29uY2F0KCc8L3Rib2R5PicpDQoJCQkkKCIjZmlsZXMtdGFiIikuYXBwZW5kKGluZXJIdG1sZmlsZXMpDQoJCX0NCg0KCQlmdW5jdGlvbiB1cGRhdGVKb2JzKCkgew0KCQkJJCgiI2pvYnNsaXN0IikuaHRtbCgiIikNCgkJCSQuYWpheCh7DQoJCQkJdXJsOiAiL2pvYnMiLA0KCQkJCXR5cGU6ICJQT1NUIiwNCgkJCQlkYXRhVHlwZTogImpzb24iDQoJCQl9KS5kb25lKGZ1bmN0aW9uKGpzb25EYXRhKSB7DQoJCQkJdmFyIGluZXJIdG1sam9icyA9ICIiDQoJCQkJZm9yIChpbmRleCBpbiBqc29uRGF0YSkgew0KCQkJCQlpbmVySHRtbGpvYnMgPSBpbmVySHRtbGpvYnMuY29uY2F0KCc8bGkgY2xhc3M9Imxpc3QtZ3JvdXAtaXRlbSI+JyArIGpzb25EYXRhW2luZGV4XSArICc8L2xpPicpDQoJCQkJfQ0KCQkJCSQoIiNqb2JzbGlzdCIpLmFwcGVuZChpbmVySHRtbGpvYnMpDQoJCQl9KQ0KCQl9DQoNCgkJZnVuY3Rpb24gc2VuZENHZXQoZSkgew0KCQkJc3RkdWlkID0gJCgiI3N0dWlkIiArIGUuaWQpLnRleHQoKQ0KCQkJYW4gPSAkKCIjYW4iICsgZS5pZCkudGV4dCgpDQoJCQlwbiA9ICQoIiNwbiIgKyBlLmlkKS50ZXh0KCkNCgkJCXBkID0gJCgiI3BkIiArIGUuaWQpLnRleHQoKQ0KCQkJc2QgPSAkKCIjc2QiICsgZS5pZCkudGV4dCgpDQoJCQl2YXIgY2ZkYXQgPSB7DQoJCQkJU2VydmVyU2V0OiB7DQoJCQkJCUFkZHJlc3M6ICQoIiNhZGRyZXNzLWlkIikudmFsKCksDQoJCQkJCVBvcnQ6ICQoIiNwb3J0LWlkIikudmFsKCksDQoJCQkJCVNlcnZlckFFX1RpdGxlOiAkKCIjYWV0aXRsZS1pZCIpLnZhbCgpDQoJCQkJfSwNCgkJCQlTdHVkeUluc3RhbmNlVUlEOiBzdGR1aWQsDQoJCQkJUGF0aWVudE5hbWU6IHBuLA0KCQkJCUFjY2Vzc2lvbk51bWJlcjogYW4sDQoJCQkJUGF0aWVuRGF0ZU9mQmlydGg6IHBkLA0KCQkJCVN0dWR5RGF0ZTogc2QNCgkJCX0NCgkJCXZhciBjZyA9IHsNCgkJCQlGaW5kUmVxOiBjZmRhdCwNCgkJCQlGb2xkZXI6IGN1cmRpcg0KCQkJfQ0KCQkJY29uc29sZS5sb2coY2cpDQoJCQkkLmFqYXgoew0KCQkJCXVybDogIi9jLWdldCIsDQoJCQkJdHlwZTogIlBPU1QiLA0KCQkJCWRhdGE6IEpTT04uc3RyaW5naWZ5KGNnKSwNCgkJCQlkYXRhVHlwZTogImpzb24iDQoJCQl9KQ0KCQl9DQoNCgkJZnVuY3Rpb24gc2VuZENTdG9yZShlKSB7DQoJCQl2YXIgZnAgPSBjdXJkaXIgKyAnLycgKyBlLmlkLnN1YnN0cmluZygyKQ0KCQkJdmFyIGNzZGF0ID0gew0KCQkJCVNlcnZlclNldDogew0KCQkJCQlBZGRyZXNzOiAkKCIjYWRkcmVzcy1pZCIpLnZhbCgpLA0KCQkJCQlQb3J0OiAkKCIjcG9ydC1pZCIpLnZhbCgpLA0KCQkJCQlTZXJ2ZXJBRV9UaXRsZTogJCgiI2FldGl0bGUtaWQiKS52YWwoKQ0KCQkJCX0sDQoJCQkJRmlsZTogZnAsDQoJCQl9DQoJCQljb25zb2xlLmxvZyhjc2RhdCkNCgkJCSQuYWpheCh7DQoJCQkJdXJsOiAiL2MtY3RvcmUiLA0KCQkJCXR5cGU6ICJQT1NUIiwNCgkJCQlkYXRhOiBKU09OLnN0cmluZ2lmeShjc2RhdCksDQoJCQkJZGF0YVR5cGU6ICJqc29uIg0KCQkJfSkNCgkJfQ0KDQoJCWZ1bmN0aW9uIE9uTG9hZCgpIHsNCgkJCWNmVGltZSA9IDAuMDsNCgkJCXVwZGF0ZVVpKCkNCgkJCQkvL3VwZGF0ZUNFY2hvU3QoKQ0KCQkJc2V0SW50ZXJ2YWwodXBkYXRlQ0VjaG9TdCwgNzAwKQ0KCQkJc2V0SW50ZXJ2YWwodXBkYXRlQ0ZpbmRTdCwgNDAwKQ0KCQkJc2V0SW50ZXJ2YWwodXBkYXRlSm9icywgMjAwMCkNCgkJCWZpcnNVcGRhdGUoKQ0KCQl9DQoNCgkJZnVuY3Rpb24gU2hvd1NlYXJjaCgpIHsNCgkJCVNob3dNZW51ID0gInNlYXJjaCINCgkJCXVwZGF0ZVVpKCkNCgkJfQ0KDQoJCWZ1bmN0aW9uIFNob3dVcGxvYWQoKSB7DQoJCQlTaG93TWVudSA9ICJ1cGxvYWQiDQoJCQl1cGRhdGVVaSgpDQoJCX0NCg0KCQlmdW5jdGlvbiBTaG93Sm9icygpIHsNCgkJCVNob3dNZW51ID0gImpvYnMiDQoJCQl1cGRhdGVKb2JzKCkNCgkJCXVwZGF0ZVVpKCkNCgkJfQ0KCTwvc2NyaXB0Pg0KPC9oZWFkPg0KDQo8Ym9keSBvbmxvYWQ9Ik9uTG9hZCgpIj4NCgk8ZGl2IGNsYXNzPSJjb250YWluZXIiPg0KCQk8ZGl2IGNsYXNzPSJ3ZWxsIj4NCgkJCTxkaXYgY2xhc3M9Im5hdmJhciBuYXZiYXItZGVmYXVsdCI+DQoJCQkJPGRpdiBjbGFzcz0iY29udGFpbmVyIj4NCgkJCQkJPGRpdiBjbGFzcz0ibmF2YmFyLWhlYWRlciI+DQoJCQkJCQk8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgY2xhc3M9Im5hdmJhci10b2dnbGUiIGRhdGEtdG9nZ2xlPSJjb2xsYXBzZSIgZGF0YS10YXJnZXQ9Ii5uYXZiYXItY29sbGFwc2UiPiA8c3BhbiBjbGFzcz0ic3Itb25seSI+VG9nZ2xlIG5hdmlnYXRpb248L3NwYW4+PHNwYW4gY2xhc3M9Imljb24tYmFyIj48L3NwYW4+PHNwYW4gY2xhc3M9Imljb24tYmFyIj48L3NwYW4+PHNwYW4gY2xhc3M9Imljb24tYmFyIj48L3NwYW4+IDwvYnV0dG9uPg0KCQkJCQk8L2Rpdj4NCgkJCQkJPGRpdiBjbGFzcz0iY29sbGFwc2UgbmF2YmFyLWNvbGxhcHNlIj4NCgkJCQkJCTx1bCBjbGFzcz0ibmF2IG5hdmJhci1uYXYiPg0KCQkJCQkJCTxsaSBvbmNsaWNrPSJTaG93U2VhcmNoKCkiPiA8YT5TZWFyY2g8L2E+IDwvbGk+DQoJCQkJCQkJPGxpIG9uY2xpY2s9IlNob3dVcGxvYWQoKSI+IDxhPlN0dWR5IFVwbG9hZDwvYT4gPC9saT4NCgkJCQkJCQk8bGkgb25jbGljaz0iU2hvd0pvYnMoKSI+IDxhPkpvYnM8L2E+IDwvbGk+DQoJCQkJCQk8L3VsPg0KCQkJCQk8L2Rpdj4NCgkJCQk8L2Rpdj4NCgkJCTwvZGl2Pg0KCQkJPGRpdiBjbGFzcz0icGFuZWwtZm9vdGVyIj5ESUNPTSBTZXJ2ZXIgc2V0dGluZ3MgPC9kaXY+DQoJCQk8dGFibGUgY2xhc3M9InRhYmxlIHRhYmxlLWJvcmRlcmVkIHRhYmxlLWNvbmRlbnNlZCB0YWJsZS1ob3ZlciB0YWJsZS1zdHJpcGVkIj4NCgkJCQk8dGJvZHk+DQoJCQkJCTx0cj4NCgkJCQkJCTx0ZD4NCgkJCQkJCQk8ZGl2IGNsYXNzPSJmb3JtLWdyb3VwIj4NCgkJCQkJCQkJPGxhYmVsIGNsYXNzPSJjb250cm9sLWxhYmVsIj5ESUNPTSBzZXJ2ZXIgYWRkcmVzczwvbGFiZWw+DQoJCQkJCQkJCTxkaXYgY2xhc3M9ImNvbnRyb2xzIj4NCgkJCQkJCQkJCTxpbnB1dCB0eXBlPSJ0ZXh0IiBjbGFzcz0iZm9ybS1jb250cm9sIGlucHV0LXNtIiBpZD0iYWRkcmVzcy1pZCIgdmFsdWU9IjE5Mi4xNjguMS4xMyI+DQoJCQkJCQkJCTwvZGl2Pg0KCQkJCQkJCTwvZGl2Pg0KCQkJCQkJPC90ZD4NCgkJCQkJCTx0ZD4NCgkJCQkJCQk8ZGl2IGNsYXNzPSJmb3JtLWdyb3VwIj4NCgkJCQkJCQkJPGxhYmVsIGNsYXNzPSJjb250cm9sLWxhYmVsIj5BRS1UaXRsZTwvbGFiZWw+DQoJCQkJCQkJCTxkaXYgY2xhc3M9ImNvbnRyb2xzIj4NCgkJCQkJCQkJCTxpbnB1dCB0eXBlPSJ0ZXh0IiBjbGFzcz0iZm9ybS1jb250cm9sIGlucHV0LXNtIiBpZD0iYWV0aXRsZS1pZCIgdmFsdWU9IkRDTTRDSEVFIj4gPC9kaXY+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQkJPHRkPg0KCQkJCQkJCTxkaXYgY2xhc3M9ImZvcm0tZ3JvdXAiPg0KCQkJCQkJCQk8bGFiZWwgY2xhc3M9ImNvbnRyb2wtbGFiZWwiPlBvcnQgbnVtYmVyPC9sYWJlbD4NCgkJCQkJCQkJPGRpdiBjbGFzcz0iY29udHJvbHMiPg0KCQkJCQkJCQkJPGlucHV0IHR5cGU9InRleHQiIGNsYXNzPSJmb3JtLWNvbnRyb2wgaW5wdXQtc20iIGlkPSJwb3J0LWlkIiB2YWx1ZT0iMTExMTIiPiA8L2Rpdj4NCgkJCQkJCQk8L2Rpdj4NCgkJCQkJCTwvdGQ+DQoJCQkJCQk8dGQ+DQoJCQkJCQkJPGRpdiBjbGFzcz0iZm9ybS1ncm91cCI+DQoJCQkJCQkJCTxsYWJlbCBjbGFzcz0iY29udHJvbC1sYWJlbCI+RElDT00gcGluZyBzdGF0dXM6PC9sYWJlbD4NCgkJCQkJCQkJPHA+DQoJCQkJCQkJCQk8bGFiZWwgY2xhc3M9ImNvbnRyb2wtbGFiZWwiIGlkPSJwYWNzLXN0YXR1cy1pZCI+T0s8L2xhYmVsPg0KCQkJCQkJCQk8L3A+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQk8L3RyPg0KCQkJCTwvdGJvZHk+DQoJCQk8L3RhYmxlPg0KCQkJPGRpdiBjbGFzcz0icGFuZWwtZm9vdGVyIiBpZD0ic2VhcmNoLWZvb3RlciI+U2VhcmNoIFNldHRpbmdzIDwvZGl2Pg0KCQkJPHRhYmxlIGlkPSJzZWFyY2gtcGFuZWwiIGNsYXNzPSJ0YWJsZSB0YWJsZS1ib3JkZXJlZCB0YWJsZS1jb25kZW5zZWQgdGFibGUtaG92ZXIgdGFibGUtc3RyaXBlZCI+DQoJCQkJPHRib2R5Pg0KCQkJCQk8dHI+DQoJCQkJCQk8dGQ+DQoJCQkJCQkJPGRpdiBjbGFzcz0iZm9ybS1ncm91cCI+DQoJCQkJCQkJCTxsYWJlbCBjbGFzcz0iY29udHJvbC1sYWJlbCI+U3R1ZHkgSW5zdGFuY2UgVUlEPC9sYWJlbD4NCgkJCQkJCQkJPGRpdiBjbGFzcz0iY29udHJvbHMiPg0KCQkJCQkJCQkJPGlucHV0IHR5cGU9InRleHQiIGNsYXNzPSJmb3JtLWNvbnRyb2wgaW5wdXQtc20iIGlkPSJzdC1pbnN0LXVpZCIgdmFsdWU9IioiPiA8L2Rpdj4NCgkJCQkJCQk8L2Rpdj4NCgkJCQkJCTwvdGQ+DQoJCQkJCQk8dGQ+DQoJCQkJCQkJPGRpdiBjbGFzcz0iZm9ybS1ncm91cCI+DQoJCQkJCQkJCTxsYWJlbCBjbGFzcz0iY29udHJvbC1sYWJlbCI+QWNjZXNzaW9uIG51bWJlcjwvbGFiZWw+DQoJCQkJCQkJCTxkaXYgY2xhc3M9ImNvbnRyb2xzIj4NCgkJCQkJCQkJCTxpbnB1dCB0eXBlPSJ0ZXh0IiBjbGFzcz0iZm9ybS1jb250cm9sIGlucHV0LXNtIiBpZD0iYWNjZXNzaW9uLW51bWJlci1pZCIgdmFsdWU9IioiPiA8L2Rpdj4NCgkJCQkJCQk8L2Rpdj4NCgkJCQkJCTwvdGQ+DQoJCQkJCQk8dGQ+DQoJCQkJCQkJPGRpdiBjbGFzcz0iZm9ybS1ncm91cCI+DQoJCQkJCQkJCTxsYWJlbCBjbGFzcz0iY29udHJvbC1sYWJlbCI+UGF0aWVudCBuYW1lPC9sYWJlbD4NCgkJCQkJCQkJPGRpdiBjbGFzcz0iY29udHJvbHMiPg0KCQkJCQkJCQkJPGlucHV0IHR5cGU9InRleHQiIGNsYXNzPSJmb3JtLWNvbnRyb2wgaW5wdXQtc20iIGlkPSJwYXRpZW50LW5hbWUtaWQiIHZhbHVlPSIqIj4gPC9kaXY+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQkJPHRkPg0KCQkJCQkJCTxkaXYgY2xhc3M9ImZvcm0tZ3JvdXAiPg0KCQkJCQkJCQk8bGFiZWwgY2xhc3M9ImNvbnRyb2wtbGFiZWwiPkRhdGUgb2YgYmlydGg8L2xhYmVsPg0KCQkJCQkJCQk8ZGl2IGNsYXNzPSJjb250cm9scyI+DQoJCQkJCQkJCQk8aW5wdXQgdHlwZT0idGV4dCIgY2xhc3M9ImZvcm0tY29udHJvbCBpbnB1dC1zbSIgaWQ9ImRhdGUtYmlydGgtaWQiIHZhbHVlPSIqIj4gPC9kaXY+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQkJPHRkPg0KCQkJCQkJCTxkaXYgY2xhc3M9ImZvcm0tZ3JvdXAiPg0KCQkJCQkJCQk8bGFiZWwgY2xhc3M9ImNvbnRyb2wtbGFiZWwiPlN0dWR5IGRhdGU8L2xhYmVsPg0KCQkJCQkJCQk8ZGl2IGNsYXNzPSJjb250cm9scyI+DQoJCQkJCQkJCQk8aW5wdXQgdHlwZT0idGV4dCIgY2xhc3M9ImZvcm0tY29udHJvbCBpbnB1dC1zbSIgaWQ9InN0dWR5LWRhdGUtaWQiIHZhbHVlPSIqIj4gPC9kaXY+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQkJPHRkPg0KCQkJCQkJCTxkaXYgY2xhc3M9ImZvcm0tZ3JvdXAiPg0KCQkJCQkJCQk8bGFiZWwgY2xhc3M9ImNvbnRyb2wtbGFiZWwiPiA8L2xhYmVsPg0KCQkJCQkJCQk8ZGl2IGNsYXNzPSJjb250cm9scyI+IDxhIG9uY2xpY2s9InNlbmRDRmluZCgpIiBjbGFzcz0iYnRuIHB1bGwtbGVmdCBidG4taW5mbyI+RiBJIE4gRDwvYT4gPC9kaXY+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQk8L3RyPg0KCQkJCTwvdGJvZHk+DQoJCQk8L3RhYmxlPg0KCQkJPGRpdiBjbGFzcz0icGFuZWwtZm9vdGVyIiBpZD0ic2VyZm9vdGVyLWlkIj5DLUZpbmQgcmVzdWx0PC9kaXY+DQoJCQk8dGFibGUgY2xhc3M9InRhYmxlIHRhYmxlLWJvcmRlcmVkIHRhYmxlLWNvbmRlbnNlZCB0YWJsZS1ob3ZlciB0YWJsZS1zdHJpcGVkIiBpZD0ic2VydGFibGUtaWQiPg0KCQkJCTx0aGVhZD4NCgkJCQkJPHRyPg0KCQkJCQkJPHRoIHN0eWxlPSJ3aWR0aDogMSU7Ij5TYXZlPC90aD4NCgkJCQkJCTx0aCBzdHlsZT0id2lkdGg6IDMlOyI+U3R1ZHkgSW5zdGFuY2UgVUlEPC90aD4NCgkJCQkJCTx0aCBzdHlsZT0id2lkdGg6IDIwJTsiPkFjY2Vzc2lvbiBudW1iZXI8L3RoPg0KCQkJCQkJPHRoPlBhdGllbnQgbmFtZTwvdGg+DQoJCQkJCQk8dGggc3R5bGU9IndpZHRoOiAyNSU7Ij5QYXRpZW50IGRhdGUgb2YgYmlydGg8L3RoPg0KCQkJCQkJPHRoIHN0eWxlPSJ3aWR0aDogMTUlOyI+U3R1ZHkgZGF0ZTwvdGg+DQoJCQkJCTwvdHI+DQoJCQkJPC90aGVhZD4NCgkJCQk8dGJvZHkgaWQ9InNlcmNocmVzbGlzdCI+IDwvdGJvZHk+DQoJCQk8L3RhYmxlPg0KCQkJPGRpdiBjbGFzcz0icGFuZWwtZm9vdGVyIiBpZD0idXBsb2FkZm9vdGVyLWlkIj5VcGxvYWQ8L2Rpdj4NCgkJCTx0YWJsZSBpZD0iZmlsZXMtdGFiIiBjbGFzcz0idGFibGUgdGFibGUtYm9yZGVyZWQgdGFibGUtc3RyaXBlZCB0YWJsZS1jb25kZW5zZWQiPg0KCQkJCTx0aGVhZD4NCgkJCQkJPHRyPg0KCQkJCQkJPHRoIHN0eWxlPSJ3aWR0aDogMSU7Ij5TZWxlY3Q8L3RoPg0KCQkJCQkJPHRoPkZpbGUgTmFtZTwvdGg+DQoJCQkJCTwvdHI+DQoJCQkJPC90aGVhZD4NCgkJCQk8dGJvZHkgaWQ9ImZpbGVzLWlkIj4NCgkJCQkJPHRyPg0KCQkJCQkJPHRkPg0KCQkJCQkJCTxkaXYgY2xhc3M9ImNoZWNrYm94IHB1bGwtbGVmdCI+DQoJCQkJCQkJCTxsYWJlbD4NCgkJCQkJCQkJCTxpbnB1dCB0eXBlPSJjaGVja2JveCIgdmFsdWU9InRydWUiPiA8L2xhYmVsPg0KCQkJCQkJCTwvZGl2Pg0KCQkJCQkJPC90ZD4NCgkJCQkJCTx0ZD5NaWNoYWVsPC90ZD4NCgkJCQkJCTx0ZD5ubzwvdGQ+DQoJCQkJCTwvdHI+DQoJCQkJCTx0cj4NCgkJCQkJCTx0ZD4NCgkJCQkJCQk8ZGl2IGNsYXNzPSJjaGVja2JveCBwdWxsLWxlZnQiPg0KCQkJCQkJCQk8bGFiZWw+DQoJCQkJCQkJCQk8aW5wdXQgdHlwZT0iY2hlY2tib3giIHZhbHVlPSJ0cnVlIj4gPC9sYWJlbD4NCgkJCQkJCQk8L2Rpdj4NCgkJCQkJCTwvdGQ+DQoJCQkJCQk8dGQ+TWljaGFlbDwvdGQ+DQoJCQkJCQk8dGQ+bm88L3RkPg0KCQkJCQk8L3RyPg0KCQkJCQk8dHI+DQoJCQkJCQk8dGQ+DQoJCQkJCQkJPGRpdiBjbGFzcz0iY2hlY2tib3ggcHVsbC1sZWZ0Ij4NCgkJCQkJCQkJPGxhYmVsPg0KCQkJCQkJCQkJPGlucHV0IHR5cGU9ImNoZWNrYm94IiB2YWx1ZT0idHJ1ZSI+IDwvbGFiZWw+DQoJCQkJCQkJPC9kaXY+DQoJCQkJCQk8L3RkPg0KCQkJCQkJPHRkPk1pY2hhZWw8L3RkPg0KCQkJCQkJPHRkPm5vPC90ZD4NCgkJCQkJPC90cj4NCgkJCQk8L3Rib2R5Pg0KCQkJPC90YWJsZT4NCgkJCTxkaXYgY2xhc3M9InBhbmVsLWZvb3RlciIgaWQ9ImpvYnNsaXN0Zm9vdGVyLWlkIj5Kb2JzPC9kaXY+DQoJCQk8dWwgaWQ9ImpvYnNsaXN0IiBjbGFzcz0ibGlzdC1ncm91cCI+DQoJCQkJPGxpIGNsYXNzPSJsaXN0LWdyb3VwLWl0ZW0iPkZpcnN0IEl0ZW08L2xpPg0KCQkJCTxsaSBjbGFzcz0ibGlzdC1ncm91cC1pdGVtIj5TZWNvbmQgSXRlbTwvbGk+DQoJCQkJPGxpIGNsYXNzPSJsaXN0LWdyb3VwLWl0ZW0iPlRoaXJkIEl0ZW08L2xpPg0KCQkJPC91bD4NCgkJPC9kaXY+DQoJPC9kaXY+DQo8L2JvZHk+DQoNCjwvaHRtbD4="

type FindData struct {
	FTime    int
	CfindRes []FindRes
	Refresh  bool
}

//main srv class
type DJsServ struct {
	jbBal JobBallancer
	dDisp DDisp
	fndTm int
	fRes  []FindRes
}

//start and init srv
func (srv *DJsServ) Start(listenPort int) error {
	srv.jbBal.Init(&srv.dDisp, srv, srv)
	srv.dDisp.dCln.CallerAE_Title = "AE_DTLS"
	http.HandleFunc("/c-echo", srv.cEcho)
	http.HandleFunc("/c-find", srv.cFind)
	http.HandleFunc("/c-get", srv.cGet)
	http.HandleFunc("/c-finddat", srv.cFindData)
	http.HandleFunc("/c-ctore", srv.cStore)
	http.HandleFunc("/index.html", srv.index)
	http.HandleFunc("/chd", srv.chd)
	http.HandleFunc("/jobs", srv.jobs)
	if err := http.ListenAndServe(":"+strconv.Itoa(listenPort), nil); err != nil {
		return errors.New("error: can't start listen http server")
	}
	return nil
}

//serve cEcho responce
func (srv *DJsServ) cEcho(rwr http.ResponseWriter, req *http.Request) {
	defer req.Body.Close()
	bodyData, err := ioutil.ReadAll(req.Body)
	if err != nil {
		strErr := "error: Can't read http body data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	var dec EchoReq
	if err := json.Unmarshal(bodyData, &dec); err != nil {
		strErr := "error: can't parse DicomCEchoRequest data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}

	ech, err := srv.dDisp.Dispatch(dec)
	if err != nil {
		log.Printf("error: can't push job")
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		return

	}

	js, err := json.Marshal(ech)
	if err != nil {
		log.Printf("error: can't serialize servise state")
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		return
	}
	rwr.Write(js)
}

//serve cEcho responce
func (srv *DJsServ) cFind(rwr http.ResponseWriter, req *http.Request) {
	defer req.Body.Close()
	bodyData, err := ioutil.ReadAll(req.Body)
	if err != nil {
		strErr := "error: Can't read http body data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	var fr FindReq
	if err := json.Unmarshal(bodyData, &fr); err != nil {
		strErr := "error: can't parse cFind data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}

	if err := srv.jbBal.PushJob(fr); err != nil {
		log.Printf("error: can't push job")
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		return

	}
	//return non error empty data
	rwr.Write([]byte{0})
}

func (srv *DJsServ) cGet(rwr http.ResponseWriter, req *http.Request) {
	defer req.Body.Close()
	bodyData, err := ioutil.ReadAll(req.Body)
	if err != nil {
		strErr := "error: Can't read http body data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	var cg CGetReq
	if err := json.Unmarshal(bodyData, &cg); err != nil {
		strErr := "error: can't parse cGet data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}

	if err := srv.jbBal.PushJob(cg); err != nil {
		log.Printf("error: can't push job")
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		return

	}
	//return non error empty data
	rwr.Write([]byte{0})
}

//serve find data responce
func (srv *DJsServ) cFindData(rwr http.ResponseWriter, req *http.Request) {
	defer req.Body.Close()
	bodyData, err := ioutil.ReadAll(req.Body)
	if err != nil {
		strErr := "error: Can't read http body data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	var lctim int
	if err := json.Unmarshal(bodyData, &lctim); err != nil {
		strErr := "error: can't parse time data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	if lctim != srv.fndTm {
		fdat := FindData{Refresh: true, CfindRes: srv.fRes, FTime: srv.fndTm}
		js, err := json.Marshal(fdat)
		if err != nil {
			log.Printf("error: can't serialize cfind data")
			http.Error(rwr, err.Error(), http.StatusInternalServerError)
			return
		}
		rwr.Write(js)
	} else {
		fdat := FindData{Refresh: false}
		js, err := json.Marshal(fdat)
		if err != nil {
			log.Printf("error: can't serialize cfind data")
			http.Error(rwr, err.Error(), http.StatusInternalServerError)
			return
		}
		rwr.Write(js)
	}

}

//serve main page request
func (srv *DJsServ) index(rwr http.ResponseWriter, req *http.Request) {
	rwr.Header().Set("Content-Type: text/html", "*")

	content, err := ioutil.ReadFile("index.html")
	if err != nil {
		log.Println("warning: start page not found, return included page")
		val, _ := base64.StdEncoding.DecodeString(htmlData)
		rwr.Write(val)
		return
	}
	rwr.Write(content)
}

func (srv *DJsServ) DispatchError(fjb FaJob) error {
	log.Print("info: dispatch error ")
	log.Println(fjb.ErrorData)
	return nil
}

func (srv *DJsServ) DispatchSuccess(cjb CompJob) error {
	log.Printf("info: dispatch success %v", cjb)
	switch result := cjb.ResultData.(type) {
	case []FindRes:
		return srv.onCFindDone(result)
	case CStorReq:
		log.Printf("info: cstore succesuly complete %v", result)
	case CGetReq:
		log.Printf("info: cget succesuly complete %v", result)
	default:
		log.Printf("warning: unexpected job type %v", result)
	}
	return nil
}

func (srv *DJsServ) onCFindDone(fres []FindRes) error {
	srv.fRes = fres
	srv.fndTm = time.Now().Nanosecond()
	return nil
}

func (srv *DJsServ) jobs(rwr http.ResponseWriter, req *http.Request) {
	if jobs, err := srv.jbBal.GetJobsList(); err != nil {
		log.Printf("error: can't get jobs list data")
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
	} else {
		js, err := json.Marshal(jobs)
		if err != nil {
			log.Printf("error: can't serialize jobs list data")
			http.Error(rwr, err.Error(), http.StatusInternalServerError)
			return
		}
		rwr.Write(js)
	}

}
func (srv *DJsServ) chd(rwr http.ResponseWriter, req *http.Request) {
	defer req.Body.Close()

	bodyData, err := ioutil.ReadAll(req.Body)
	if err != nil {
		strErr := "error: Can't read http body data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	var chd struct {
		New    string
		CurDir string
	}
	if err := json.Unmarshal(bodyData, &chd); err != nil {
		strErr := "error: can't parse new dir data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}

	dir, ls, err := Lsd(chd.CurDir + string(os.PathSeparator) + chd.New)
	if err != nil {
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
	}
	var rd struct {
		Files  []Finfo
		CurDir string
	}
	rd.CurDir = dir
	rd.Files = ls
	js, err := json.Marshal(rd)
	if err != nil {
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		return
	}
	rwr.Write(js)
}

func (srv *DJsServ) cStore(rwr http.ResponseWriter, req *http.Request) {
	defer req.Body.Close()
	bodyData, err := ioutil.ReadAll(req.Body)
	if err != nil {
		strErr := "error: Can't read http body data"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	var cstr CStorReq
	if err := json.Unmarshal(bodyData, &cstr); err != nil {
		strErr := "error: can't parse c-strore date"
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		log.Println(strErr)
		return
	}
	if err := srv.jbBal.PushJob(cstr); err != nil {
		log.Printf("error: can't push job")
		http.Error(rwr, err.Error(), http.StatusInternalServerError)
		return

	}
	rwr.Write([]byte{0})
}
